# Generated by Django 5.1.7 on 2025-06-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "description",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateField(auto_now=True)),
            ],
        ),
    ]
